object Versions {
    const val gradle = "7.0.2"
    const val kotlin = "1.5.0"
    const val kotlin_coroutines = "1.5.0"
    const val kotlin_viewmodel_ktx = "2.3.1"
    const val kotlin_core_ktx = "1.3.1"
    const val kotlin_lifecycle_livedata_ktx = "2.3.0-beta01"
    const val kotPref = "2.12.0"
    const val lifecycle = "2.2.0"
    const val support = "1.3.0"
    const val constraint_layout = "2.0.4"
    const val junit = "4.13"
    const val gson = "2.8.6"
    const val firebase_crashlytics = "17.2.2"
    const val firebase = "17.5.0"
    const val room = "2.3.0"
    const val timber = "4.7.1"
    const val hilt = "1.0.0"
    const val android_hilt = "2.38.1"
    const val navigation = "2.3.5"
    const val input_mask = "6.0.0"
    const val ktlint = "10.0.0"
    const val kex = "0.1.3.4"
    const val sresult = "1.3.31"
}